import { Article, KnowledgeCategory } from "@/types/knowledge";

export const mockArticles: Article[] = [
  {
    id: "1",
    slug: "what-should-i-do-during-an-arrest",
    title: "What should I do during an arrest?",
    excerpt:
      "Being arrested is a stressful and confusing experience. Understanding your rights and the proper steps can help protect you.",
    body: [
      "Being arrested is one of the most stressful experiences a person can face. Your actions in the first few minutes can significantly affect the outcome of your case.",
      "",
      "## Immediate Steps",
      'The moment an officer indicates you are being arrested, invoke your right to remain silent clearly: "I am exercising my right to remain silent and I want a lawyer." After saying this, stop talking.',
      "",
      "## Physical Compliance",
      "Even if you believe the arrest is unlawful, do not resist physically. Resisting arrest is itself a criminal offence. Challenge the arrest through legal means — in court, with a lawyer.",
      "",
      "## Your Rights During Arrest",
      "You have the right to know the reason for your arrest. You have the right to remain silent. You have the right to legal representation. You have the right to be treated with dignity and to not be subjected to torture or degrading treatment.",
      "",
      "## After Arrest",
      "You must be charged or released within a reasonable time. You have the right to contact your lawyer and your family. Any statement made without your lawyer present can potentially be challenged in court.",
      "",
      "## Important Note",
      "This article provides general information only. Every arrest situation is unique. Contact a qualified criminal defense lawyer as soon as possible.",
    ].join("\n"),
    category: KnowledgeCategory.CRIMINAL_RIGHTS,
    readTimeMinutes: 4,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    slug: "can-police-search-my-phone",
    title: "Can police search my phone?",
    excerpt:
      "Your smartphone contains a vast amount of personal information. Learn when police can legally access your device.",
    body: [
      "Your smartphone contains a vast amount of personal information, from messages and photos to financial and location data. The law treats access to it differently from a normal search.",
      "",
      "## When Police Can Search Your Phone",
      "Police generally need a warrant, your informed consent, or a clear lawful exception, such as evidence in plain view, to search the contents of your phone. Simply being arrested does not automatically give officers the right to go through it.",
      "",
      "## Your Right to Refuse Consent",
      "You are not required to unlock your phone or provide your passcode on request. You can politely state that you do not consent to a search. Asking for a lawyer is not obstruction, and refusal alone is not evidence of guilt.",
      "",
      "## If Your Phone Is Seized",
      "If officers take your phone, ask why, and note the time, location, and the officer's name and badge number. Ask for a receipt or written record of the seizure. Do not attempt to delete anything, as this can create separate legal problems.",
      "",
      "## Important Note",
      "This article provides general information only. Whether a specific search was lawful depends on the facts. Speak to a lawyer if your phone has been searched or seized.",
    ].join("\n"),
    category: KnowledgeCategory.PRIVACY_RIGHTS,
    readTimeMinutes: 3,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "3",
    slug: "what-are-my-tenant-rights",
    title: "What are my tenant rights?",
    excerpt:
      "As a tenant, you have significant legal protections. Landlords cannot simply evict you without proper cause.",
    body: [
      "As a tenant, you have significant legal protections. A landlord cannot simply lock you out, seize your belongings, or force you to leave without following the proper legal process.",
      "",
      "## Your Right to Notice",
      "A landlord must give you proper written notice before ending a tenancy, and the required notice period depends on your agreement and how rent is paid. Verbal warnings alone are not enough to remove you.",
      "",
      "## Self-Help Eviction Is Not Allowed",
      "A landlord cannot change your locks, cut off electricity or water, or remove your property to force you out. These actions are unlawful even if rent is genuinely owed, and a court process must be followed instead.",
      "",
      "## Repairs and Habitability",
      "You are entitled to a property that is safe and habitable. Document any disrepair with photos and written requests to your landlord, and keep copies of everything you send.",
      "",
      "## If You Are Threatened With Eviction",
      "Keep your tenancy agreement, rent receipts, and all correspondence with your landlord. Do not move out under pressure before understanding whether the notice you received is valid.",
      "",
      "## Important Note",
      "This article provides general information only. Tenancy rules vary by state and by the terms of your agreement. Speak to a lawyer before responding to an eviction notice.",
    ].join("\n"),
    category: KnowledgeCategory.PROPERTY_LAW,
    readTimeMinutes: 5,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "4",
    slug: "how-do-i-report-fraud",
    title: "How do I report fraud?",
    excerpt:
      "If you have been a victim of fraud, you have several reporting options in Nigeria.",
    body: [
      "If you have been a victim of fraud, acting quickly and keeping clear records improves your chances of recovering funds and helps investigators build a case.",
      "",
      "## Gather Your Evidence First",
      "Collect bank statements, transaction alerts, chat or call logs, emails, and screenshots of any messages from the person or platform involved. Note the exact dates, amounts, and account details.",
      "",
      "## Report to Your Bank Immediately",
      "If money left your account, contact your bank's fraud desk right away to request a transaction reversal or freeze on the receiving account. Acting within hours, not days, matters.",
      "",
      "## Reporting Options in Nigeria",
      "You can report to the Nigeria Police Force, the EFCC, or the NPF's Cybercrime unit, depending on the nature of the fraud. Bring your evidence and a written account of what happened when you file a report.",
      "",
      "## What Happens Next",
      "You should receive a case or reference number from any agency you report to. Keep it, and follow up periodically. Recovery is not guaranteed, but a prompt, well-documented report gives investigators the best chance.",
      "",
      "## Important Note",
      "This article provides general information only. If a large sum is involved, or the fraud is ongoing, speak to a lawyer alongside filing a report.",
    ].join("\n"),
    category: KnowledgeCategory.FINANCIAL_CRIME,
    readTimeMinutes: 4,
    createdAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "5",
    slug: "understanding-efcc-invitations",
    title: "Understanding EFCC invitations",
    excerpt:
      "Receiving an EFCC invitation does not mean you are guilty of anything. It simply means you are required to provide information.",
    body: [
      "Receiving an EFCC invitation does not mean you are guilty of anything. It simply means the agency believes you can provide information relevant to a matter it is looking into.",
      "",
      "## Confirm the Invitation Is Genuine",
      "Verify the issuing office, the reference number, and the date on the letter, and confirm it through the EFCC's official contact channels before responding. Fraudulent invitations do circulate.",
      "",
      "## Do Not Ignore It",
      "Ignoring a genuine invitation can lead to further legal steps against you. At the same time, do not attend without first understanding what the matter concerns.",
      "",
      "## Speak to a Lawyer First",
      "Contact a lawyer before making any statement or handing over documents. A lawyer can accompany you and advise you on what you are and are not required to disclose.",
      "",
      "## What to Bring",
      "Bring only the specific documents requested in the invitation, along with valid identification. Keep copies of everything you submit, and request a written record of what was discussed.",
      "",
      "## Important Note",
      "This article provides general information only. Every invitation is different, and how you should respond depends on the details of your specific case.",
    ].join("\n"),
    category: KnowledgeCategory.FINANCIAL_CRIME,
    readTimeMinutes: 6,
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "6",
    slug: "vehicle-seizure-your-rights",
    title: "Vehicle seizure: your rights",
    excerpt:
      "If your vehicle has been seized by authorities, there are defined legal procedures that must be followed.",
    body: [
      "If your vehicle has been seized by authorities, there are defined legal procedures that must be followed, and you have rights throughout the process.",
      "",
      "## Ask for the Reason and Documentation",
      "Ask the officer why your vehicle is being seized and request a written seizure notice or receipt. Note the officer's name, badge number, the time, and the location.",
      "",
      "## When Seizure Is Lawful",
      "Vehicles can generally be seized as evidence, for unpaid fines, for expired documentation, or when linked to a suspected offence. An officer should be able to state a specific legal basis for the seizure.",
      "",
      "## Getting Your Vehicle Back",
      "Ask where the vehicle will be held and what steps are needed to reclaim it. Keep every receipt, notice, and reference number you are given, since these are usually required to process a release.",
      "",
      "## If You Believe the Seizure Was Unlawful",
      "Do not attempt to forcibly retrieve the vehicle yourself. Document everything as soon as it is safe to do so, and raise the matter through the proper complaint channel or with a lawyer.",
      "",
      "## Important Note",
      "This article provides general information only. The correct process depends on the reason given for the seizure. Speak to a lawyer if your vehicle is not released within a reasonable time.",
    ].join("\n"),
    category: KnowledgeCategory.TRAFFIC_LAW,
    readTimeMinutes: 3,
    createdAt: "2024-03-01T10:00:00Z",
  },
];