import { Lawyer, LawyerDetail } from "@/types/lawyers";

export const mockLawyers: Lawyer[] = [
  {
    id: "1",
    slug: "adaeze-okonkwo",
    name: "Adeaze Okonkwo",
    specialty: "Criminal Law",
    subSpecialties: ["Criminal Defense", "Human Rights", "Constitutional Law"],
    rating: 4.9,
    reviews: 128,
    price: 15000,
    responseTime: "2 min",
    availability: true,
  },
  {
    id: "2",
    slug: "emeka-nwosu",
    name: "Emeka Nwosu",
    specialty: "Civil Rights",
    subSpecialties: ["Human Rights", "Civil Rights"],
    rating: 4.8,
    reviews: 94,
    price: 12000,
    responseTime: "5 min",
    availability: true,
  },
  {
    id: "3",
    slug: "fatima-al-hassan",
    name: "Fatima Al-Hassan",
    specialty: "Employment Law",
    subSpecialties: ["Civil Rights", "Employment", "Labour Relations"],
    rating: 4.7,
    reviews: 67,
    price: 10000,
    responseTime: "10 min",
    availability: true,
  },
  {
    id: "4",
    slug: "oluwaseun-adeyemi",
    name: "Oluwaseun Adeyemi",
    specialty: "Property Law",
    subSpecialties: ["Land Disputes", "Property Rights"],
    rating: 4.8,
    reviews: 112,
    price: 18000,
    responseTime: "3 min",
    availability: true,
  },
  {
    id: "5",
    slug: "chiamaka-eze",
    name: "Chiamaka Eze",
    specialty: "Family Law",
    subSpecialties: ["Domestic Violence", "Family Court"],
    rating: 4.9,
    reviews: 145,
    price: 13000,
    responseTime: "4 min",
    availability: true,
  },
];

export const mockLawyerDetails: Record<string, LawyerDetail> = {
  "adaeze-okonkwo": {
    id: "1",
    slug: "adaeze-okonkwo",
    name: "Adeaze Okonkwo",
    specialty: "Criminal Law",
    subSpecialties: ["Criminal Defense", "Human Rights", "Constitutional Law"],
    rating: 4.9,
    reviews: 128,
    price: 15000,
    responseTime: "2 min",
    availability: true,
    experience: 12,
    location: "Lagos, Nigeria",
    barNumber: "NBA-LAG-2012",
    languages: ["English", "Igbo"],
    about: "Adeaze Okonkwo is a seasoned criminal defense lawyer with over 12 years of experience in the Nigerian legal system. She is passionate about protecting the rights of the accused and has successfully handled numerous high-profile cases.",
    practiceAreas: ["Criminal Defense", "Human Rights", "Police Matters"],
  },
  "emeka-nwosu": {
    id: "2",
    slug: "emeka-nwosu",
    name: "Emeka Nwosu",
    specialty: "Civil Rights",
    subSpecialties: ["Human Rights", "Civil Rights"],
    rating: 4.8,
    reviews: 94,
    price: 12000,
    responseTime: "5 min",
    availability: true,
    experience: 8,
    location: "Abuja, Nigeria",
    barNumber: "NBA-ABJ-2015",
    languages: ["English", "Hausa"],
    about: "Emeka Nwosu is a dedicated civil rights lawyer committed to defending the rights of citizens against state abuse.",
    practiceAreas: ["Human Rights", "Civil Rights", "Constitutional Law"],
  },
  "fatima-al-hassan": {
    id: "3",
    slug: "fatima-al-hassan",
    name: "Fatima Al-Hassan",
    specialty: "Employment Law",
    subSpecialties: ["Civil Rights", "Employment", "Labour Relations"],
    rating: 4.7,
    reviews: 67,
    price: 10000,
    responseTime: "10 min",
    availability: true,
    experience: 6,
    location: "Kano, Nigeria",
    barNumber: "NBA-KAN-2016",
    languages: ["English", "Hausa", "Arabic"],
    about: "Fatima Al-Hassan specializes in employment and labour law, helping employees and employers navigate workplace disputes.",
    practiceAreas: ["Employment", "Labour Relations", "Civil Rights"],
  },
  "oluwaseun-adeyemi": {
    id: "4",
    slug: "oluwaseun-adeyemi",
    name: "Oluwaseun Adeyemi",
    specialty: "Property Law",
    subSpecialties: ["Land Disputes", "Property Rights"],
    rating: 4.8,
    reviews: 112,
    price: 18000,
    responseTime: "3 min",
    availability: true,
    experience: 10,
    location: "Ibadan, Nigeria",
    barNumber: "NBA-IBD-2013",
    languages: ["English", "Yoruba"],
    about: "Oluwaseun Adeyemi is a property law expert with extensive experience in land disputes and property rights.",
    practiceAreas: ["Land Disputes", "Property Rights", "Real Estate"],
  },
  "chiamaka-eze": {
    id: "5",
    slug: "chiamaka-eze",
    name: "Chiamaka Eze",
    specialty: "Family Law",
    subSpecialties: ["Domestic Violence", "Family Court"],
    rating: 4.9,
    reviews: 145,
    price: 13000,
    responseTime: "4 min",
    availability: true,
    experience: 7,
    location: "Enugu, Nigeria",
    barNumber: "NBA-ENU-2017",
    languages: ["English", "Igbo"],
    about: "Chiamaka Eze is a compassionate family lawyer dedicated to protecting families and children in legal disputes.",
    practiceAreas: ["Domestic Violence", "Family Court", "Child Custody"],
  },
};